/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"

bool_t
xdr_rpc_minify_in (XDR *xdrs, rpc_minify_in *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->src.src_val, (u_int *) &objp->src.src_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->src_len))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->dst_len))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rpc_minify_out (XDR *xdrs, rpc_minify_out *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->dest.dest_val, (u_int *) &objp->dest.dest_len, ~0))
		 return FALSE;
	return TRUE;
}
