/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct rpc_minify_in {
	struct {
		u_int src_len;
		char *src_val;
	} src;
	int src_len;
	int dst_len;
};
typedef struct rpc_minify_in rpc_minify_in;

struct rpc_minify_out {
	struct {
		u_int dest_len;
		char *dest_val;
	} dest;
};
typedef struct rpc_minify_out rpc_minify_out;

#define RPC_MINIFY_JPEG_PROG 0x31230000
#define RPC_MINIFY_JPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RPC_MINIFY_JPEG_PROC 1
extern  rpc_minify_out * rpc_minify_jpeg_proc_1(rpc_minify_in , CLIENT *);
extern  rpc_minify_out * rpc_minify_jpeg_proc_1_svc(rpc_minify_in , struct svc_req *);
extern int rpc_minify_jpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RPC_MINIFY_JPEG_PROC 1
extern  rpc_minify_out * rpc_minify_jpeg_proc_1();
extern  rpc_minify_out * rpc_minify_jpeg_proc_1_svc();
extern int rpc_minify_jpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_rpc_minify_in (XDR *, rpc_minify_in*);
extern  bool_t xdr_rpc_minify_out (XDR *, rpc_minify_out*);

#else /* K&R C */
extern bool_t xdr_rpc_minify_in ();
extern bool_t xdr_rpc_minify_out ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
