/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

rpc_minify_out *
rpc_minify_jpeg_proc_1(rpc_minify_in arg1,  CLIENT *clnt)
{
	static rpc_minify_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RPC_MINIFY_JPEG_PROC,
		(xdrproc_t) xdr_rpc_minify_in, (caddr_t) &arg1,
		(xdrproc_t) xdr_rpc_minify_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
